#!/bin/bash

set -e

function cleanup {
    set +e
    kill `jobs -p`
}

trap cleanup EXIT

# Run the unit tests
PYTHONPATH=.:$PYTHONPATH python test/test_models.py

# Start the server
pushd test/static
python -m SimpleHTTPServer &
popd

# Run the integration tests
PYTHONPATH=.:$PYTHONPATH ./scripts/catnap test/integration_test.yaml
